services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rgo_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
    ports:
      - "8000:8000"
    networks:
      - rgo_network

networks:
  rgo_network:
    driver: bridge
