services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-laravel-app:prod
    container_name: laravel_app
    restart: unless-stopped
    env_file:
      - .env.prod
    volumes:
      - app_code:/var/www/html
      - app_logs:/var/www/html/storage/logs
    expose:
      - "9000"
    networks:
      - app_net

  nginx:
    image: nginx:1.27-alpine
    container_name: laravel_nginx
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - app_code:/var/www/html:ro
      - ./docker/nginx/nginx.http.conf:/etc/nginx/nginx.conf:ro
      - ./docker/letsencrypt:/etc/letsencrypt:ro      # ใบรับรองจริง
      - ./docker/letsencrypt-var:/var/lib/letsencrypt # ข้อมูล certbot/renew
      - ./docker/acme:/var/www/acme:ro                # ✅ webroot สำหรับ ACME challenge
    networks:
      - app_net

volumes:
  app_code:
  app_logs:

networks:
  app_net:
    driver: bridge
