events {}
http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;
  sendfile      on;

  server {
    listen 80;
    server_name rgo.intercrop.co.th;

    location ^~ /.well-known/acme-challenge/ {
      root /var/www/certbot;
    }

    location / {
      return 301 https://$host$request_uri;
    }
  }

  server {
    listen 443 ssl http2;
    server_name rgo.intercrop.co.th;

    root /var/www/html/public;
    index index.php index.html;

    ssl_certificate     /etc/letsencrypt/live/rgo.intercrop.co.th/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/rgo.intercrop.co.th/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    location ~* \.(jpg|jpeg|png|gif|ico|css|js|svg|woff|woff2|ttf)$ {
      try_files $uri =404;
      access_log off;
      expires 7d;
    }

    location / {
      try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
      include        fastcgi_params;
      fastcgi_pass   app:9000;
      fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
      fastcgi_param  PATH_INFO $fastcgi_path_info;
    }
  }
}
