server {
    listen 80;
    server_name localhost;
    root /var/www/html/public;

    index index.php index.html index.htm;

    error_log /var/log/nginx/error.log notice; # <--- เพิ่มตรงนี้

    access_log /var/log/nginx/access.log; # <--- อาจจะเพิ่ม access log ทั่วไปของ server block ด้วยก็ได้ (ถ้ายังไม่มี)

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        # try_files $uri =404; # ลองปิดบรรทัดนี้ไปก่อนชั่วคราว
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info; # เพิ่ม PATH_INFO
        include fastcgi_params;

        access_log /var/log/nginx/php_access.log; # <--- access log สำหรับ PHP
    }

    location ~ /\.ht {
        deny all;
    }
}
